#- platform: foscam
  #ip: 10.10.10.205
  #username: !secret foscam_username
  #password: !secret foscam_pwd
  #name: "Camera Salone R2"
- platform: generic
  still_image_url: http://api.sat24.com/animated/IT/visual/1/Central%20European%20Standard%20Time/2380259'%20width=400%20height=291
  name: Italia
- platform: generic
  name: Pier
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.pier_ipier.attributes.latitude }},{{ states.device_tracker.pier_ipier.attributes.longitude }}&zoom=15&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:P%7C{{ states.device_tracker.pier_ipier.attributes.latitude }},{{ states.device_tracker.pier_ipier.attributes.longitude }}
  limit_refetch_to_url_change: true
- platform: generic
  name: Costanza
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.costanza_icostanza.attributes.latitude }},{{ states.device_tracker.costanza_icostanza.attributes.longitude }}&zoom=15&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:P%7C{{ states.device_tracker.costanza_icostanza.attributes.latitude }},{{ states.device_tracker.costanza_icostanza.attributes.longitude }}
  limit_refetch_to_url_change: true
