#- platform: owntracks
- platform: nmap_tracker
  track_new_devices: false
  interval_seconds: 30
  consider_home: 600
  home_interval: 10
  scan_options: " --privileged -sP "
  hosts:
    - 192.168.1.16
    - 192.168.1.113
#- platform: netgear
#host: 192.168.1.42
#  username: admin
#  password: password
